---
# Zookeeper variables
zookeeper_client_port: "2181"
zookeeper_server_group: zookeeper_servers

zookeeper_peers_nodes: "
	{%- if zookeeper_peers is defined -%}
            {% for host in zookeeper_peers %}{{host}}:{{zookeeper_client_port}}{% if not loop.last %},{% endif %}{% endfor %}
	{%- else -%}
	    {%- set zookeeper_peers = [] -%}
	    {%- for host in groups[zookeeper_server_group] -%}
	      {%- if host not in zookeeper_peers -%}
	        {%- set current_host = hostvars[host]['ansible_eth0']['ipv4']['address'] + ':' + zookeeper_client_port -%}
	        {%- do zookeeper_peers.append(current_host) -%}
	      {%- endif -%}
	    {%- endfor -%}
	    {{ zookeeper_peers|join(',') }}
	{%- endif -%}
"

# defaults file for chronos
openssl_self_signed:
 - { name : "chronos.service.consul" }
generate_random_pass: "true"
chronos_key_password: "password"
chronos_pkcs_password: "password"
chronos_jks_password: "password"
chronos_username: "admin"
chronos_password: "secr3t"
chronos_version: 'latest'
chronos_hostname: "{{ ansible_default_ipv4.address }}"
chronos_framework_name: "chronos"
chronos_port: '4400'
chronos_https_port: '4443'
chronos_keystore_path: '/etc/chronos/ssl_keystore.jks'
chronos_server_zk_group: chronos_servers
chronos_image: "indigodatacloud/chronos:{{ chronos_version }}"
chronos_master_peers: "zk://{{ zookeeper_peers_nodes }}/mesos"
chronos_zk_peers: "zk://{{ zookeeper_peers_nodes }}"

chronos_ssl_ks_password: "
   {%- if generate_random_pass|string() == 'true' -%}
	    {{ chronos_jks_randpassword.stdout  }}
   {%- else -%}
            {{ chronos_jks_password }}
   {%- endif -%}
"


